name = "feishu-cms-proxy"
type = "javascript"

account_id = "your-account-id"
workers_dev = true
env = {
  FEISHU_APP_ID = "",
  FEISHU_APP_SECRET = "",
  FEISHU_APP_TOKEN = "O0MmbvnrbahpTFsc0Nzczkl3nVf",
  FEISHU_TABLE_ID = "tblti06E1WY7GwoE"
}

[build]
command = ""
